name: Go package

on: [push]

jobs:
  go-tools:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.18'

      - name: go fmt
        run: go fmt ./...

      - name: git diff
        run: git diff --exit-code

      - name: go vet
        run: go vet -v ./...

      - name: go test
        run: go test -v ./...

      - name: openssl
        run: :|openssl s_client -connect juniper.net:443 -showcerts

      - name: printenv
        run: printenv

#      - name: hexdump
#        run: hexdump -C <<< ${{ secrets.NON_ENV_SECRET }}
